#!/bin/sh

sleepsec=15

while true; do
	# if you start this from .xinitrc, the script will start before
	# awesome, and will fail.
	if [ -S ~/.awesome_ctl.0 ]; then
		while true; do
			status=$(acpi -b | awk '{print $3}')
			charge_percent=$(acpi -b | grep -o '[0-9]*%')

			case $status in
			Charging*)
				status_text=" +"
				;;
			Discharging*)
				status_text=" -"
				;;
			Full*)
				status_text=" ="
				;;
			esac

			#echo "0 widget_tell mystatusbar battery data bat0 $charge_percent"
			echo "0 widget_tell mystatusbar battery text $charge_percent $status_text"
			echo "" # an empty line flushes data inside awesome
			sleep $sleepsec
		done | awesome-client
	else
		sleep 1
	fi
done
