#!/bin/sh

sleepsec=1

while true; do
	# if you start this from .xinitrc, the script will start before
	# awesome, and will fail.
	if [ -S ~/.awesome_ctl.0 ]; then
		while true; do
			echo "0 widget_tell mystatusbar clock text $(date +'%F %T')"
			echo "" # an empty line flushes data inside awesome
			sleep $sleepsec
		done | awesome-client
	else
		sleep 1
	fi
done
