#!/usr/bin/env python3

import argparse
from datetime import datetime
import os
import subprocess
import sys

TARGETS = ['~']
PLATFORM_TARGETS = {'darwin': ['/nix', '/usr/local']}
DATE_FILE = os.path.expanduser('~/.backup-laptop-dates')


def run_command(command, dry_run=False):
    command = ['echo'] + command if dry_run else command
    subprocess.run(command, check=True)


def eject_drive(path, dry_run=False):
    if sys.platform == 'darwin':
        run_command(['diskutil', 'eject', path], dry_run=dry_run)


def targets():
    extra_targets = PLATFORM_TARGETS.get(sys.platform, [])
    return [os.path.expanduser(p) for p in TARGETS + extra_targets]


def backup(repo, dry_run):
    os.environ['RESTIC_REPOSITORY'] = repo
    run_command(['restic-gpg', 'backup',
                 '--one-file-system',
                 '--exclude', os.path.expanduser('~/.rnd')] +
                targets(), dry_run=dry_run)
    if not dry_run:
        with open(DATE_FILE, 'a') as f:
            timestamp = datetime.utcnow().isoformat()
            f.write(f'{timestamp} {repo}\n')


def run(*, repo, eject=True, dry_run=False):
    repo = os.path.normpath(repo)
    backup(repo, dry_run=dry_run)
    if eject:
        eject(os.path.dirname(repo), dry_run=dry_run)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Backup laptop',
        argument_default=argparse.SUPPRESS)
    parser.add_argument(
        'repo',
        help='path to restic repository')
    parser.add_argument(
        '--no-eject',
        help='do not eject the drive',
        action='store_false', dest='eject')
    parser.add_argument(
        '--dry-run',
        help='dry run mode',
        action='store_true')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    sys.exit(run(**vars(args)))
