#!/bin/sh

set -e

cmd_close()
{
	# Try to close luks device, even if udisks fails
	sudo udisks --unmount /dev/mapper/luks-uuid-$UUID || true
	sudo cryptsetup luksClose luks-uuid-$UUID
}

cmd_open()
{
	gpg -d -q $HOME/.private/udisks/key.$UUID.gpg |
	sudo cryptsetup --key-file - luksOpen /dev/disk/by-uuid/$UUID luks-uuid-$UUID
	sudo udisks --mount /dev/mapper/luks-uuid-$UUID
}

cmd_format()
{
	head -c 256 /dev/random | gpg -e > $HOME/.private/udisks/key.tmp.gpg

	gpg -d -q $HOME/.private/udisks/key.$UUID.gpg | sudo cryptsetup --key-file - luksFormat /dev/$DEV
	# luksFormat changes partition UUID
	UUID=$(sudo blkid -o value -s UUID /dev/$DEV)

	mv $HOME/.private/udisks/key.tmp.gpg $HOME/.private/udisks/key.$UUID.gpg
	gpg -d -q $HOME/.private/udisks/key.$UUID.gpg | sudo cryptsetup --key-file - luksOpen /dev/disk/by-uuid/$UUID luks-uuid-$UUID
	sudo mkfs.ext4 /dev/disk/by-uuid/luks-uuid-$UUID
}

case "$1" in
close|open)
	: ${UUID:?"UUID must be set"}

	command=$1
	;;
format)
	: ${DEV:?"DEV must be set"}

	command=$1
	;;
*)
	echo "Usage: $0 {close|open|format}" >&2
	exit 3
	;;
esac
shift

"cmd_$command" "$@"
