#!/bin/sh

set -e

UUID=4d8c0053-aff4-4ed7-bd77-e82213eb149c
NAME=crypt-doc

cmd_close()
{
	sudo udisks --unmount /dev/disk/by-id/dm-name-$NAME
	sudo cryptsetup luksClose crypt-doc
}

cmd_open()
{
	gpg -d $HOME/.private/udisks/key.$UUID.gpg | sudo cryptsetup --key-file=- luksOpen /dev/disk/by-uuid/$UUID $NAME
	sudo udisks --mount /dev/disk/by-id/dm-name-$NAME
}

case "$1" in
close|open)
	command=$1
	;;
*)
	echo "Usage: $0 {close|open}" >&2
	exit 3
	;;
esac
shift

"cmd_$command" "$@"
