#!/bin/sh

case $1 in
vga)
	xrandr --output LVDS1 --off
	xrandr --output VGA1 --auto
	;;
both)
	xrandr --output LVDS1 --auto
	xrandr --output VGA1 --auto --above LVDS1
	;;
laptop)
	xrandr --output LVDS1 --auto
        xrandr --output VGA1 --off
	;;
*)
	echo "$0 laptop|vga|both"
	;;
esac
