#!/bin/sh
# Generate a .mrconfig containing all private repos

gen_mrconfig ()
{
	while read s; do
		echo "[$(dirname $s)]"
		echo "checkout = git clone gitolite@git.ciffer.net:$s.git"
		echo
	done
}

ssh gitolite@git.ciffer.net info |
# gitolite outputs list with DOS line endings
tr -d '\r' |
# Last field contains the repo name
awk '{print $NF}' |
# All private repos are under svend-priv/
grep -e '^svend-priv/' -e '^gitolite-admin$' |
gen_mrconfig |
# Delete last empty line
sed '$d'
