#!/bin/sh
# Commit current state of working tree
set -e

# Add and remove files
git add -u
git add .

# Commit changes (supress "nothing to commit" message if there are no changes)
git commit --quiet -m "Auto commit" >/dev/null
