#!/bin/sh
set -e

if [ -n "$2" ]; then
	f=$2
else
	f=$HOME/doc/accounts.txt.gpg
fi

if [ "$OSTYPE" = "cygwin" ]; then
	gpgpass "$1" $f | unix2dos | tail -n 1 | tr -d '\n' | tmclip
else
	gpgpass "$1" $f | tail -n 1 | tr -d '\n' | tmclip
fi
