#!/bin/sh

set -e

cmd_close()
{
	DEV=$1

	UUID=$(/sbin/blkid -o value -s UUID $DEV)

	# Try to close luks device, even if udisks fails
	sudo udisks --unmount /dev/disk/by-id/dm-name-luks-uuid-$UUID || true
	sudo cryptsetup luksClose luks-uuid-$UUID
}

cmd_open()
{
	DEV=$1
	KEY=$2

	UUID=$(/sbin/blkid -o value -s UUID $DEV)

	gpg -d -q $KEY |
	sudo cryptsetup --key-file - luksOpen $DEV luks-uuid-$UUID
	sudo udisks --mount /dev/mapper/luks-uuid-$UUID
}

cmd_format()
{
	DEV=$1
	KEY=$2

	head -c 256 /dev/random | gpg -e > $KEY

	gpg -d -q $KEY | sudo cryptsetup --key-file - luksFormat $DEV
	# luksFormat changes partition UUID
	UUID=$(/sbin/blkid -o value -s UUID $DEV)

	gpg -d -q $KEY |
	sudo cryptsetup --key-file - luksOpen $DEV luks-uuid-$UUID
	sudo mkfs.ext4 /dev/mapper/luks-uuid-$UUID
}

case "$1" in
close|open)
	command=$1
	;;
format)
	command=$1
	;;
*)
	echo "Usage: $0 open <dev> <keyfile>" >&2
	echo "Usage: $0 close <dev>" >&2
	echo "Usage: $0 format <dev> <keyfile>" >&2
	exit 3
	;;
esac
shift

"cmd_$command" "$@"
