#!/bin/sh

set -e

UUID=$(basename *.gpg .gpg)

gpg --import publickey.asc
gpg --card-status
./gpg-luks open $UUID $UUID.gpg
sudo udisks --unmount /dev/mapper/luks-uuid-$UUID
sudo mount /dev/mapper/luks-uuid-$UUID /home
