#!/usr/bin/env python3

import subprocess
import sys


def certs(iterator):
    """Yields certificates from iterator."""
    BEGIN = '-----BEGIN'
    END = '-----END'

    it = iter(iterator)
    cert_lines = []
    in_cert = False
    for line in it:
        if line.startswith(BEGIN):
            in_cert = True
        if in_cert:
            cert_lines.append(line)
            if line.startswith(END):
                in_cert = False
                yield ''.join(cert_lines)


if __name__ == '__main__':
    command = sys.argv[1:]
    if not command:
        command = ["cat"]
    for cert in certs(sys.stdin):
        subprocess.run(command, input=str.encode(cert))
