#!/usr/bin/env python3

import subprocess
import sys

END = '-----END'


def certs(iterator):
    it = iter(iterator)
    cert_lines = []
    for line in it:
        cert_lines.append(line)
        if line.startswith(END):
            yield ''.join(cert_lines)


if __name__ == '__main__':
    command = sys.argv[1:]
    for cert in certs(sys.stdin):
        subprocess.run(command, input=str.encode(cert))
