#!/bin/sh
# Update shebang for current nix installed python

set -e

PYTHON_BIN_PATH=$(python -E -m site --user-base)/bin
PYTHON_BIN=$(readlink -f "$(which python2.7)")

find "$PYTHON_BIN_PATH" -maxdepth 1 -type f -print0 \
  | xargs -0 sed -i "s|#!/nix/store/.*/bin/python2.7|#!$PYTHON_BIN|"
