#!/bin/bash

# Run notmuch on remote host
#
# http://notmuchmail.org/remoteusage/
#
# Put (setq notmuch-command "notmuch-remote) in emacs configuration.

# Start a ControlMaster connection first:

ssh -O check garnet.ciffer.net 2>/dev/null ||
ssh -MNf garnet.ciffer.net

# ControlPersist option (in OpenSSH 5.6) would be very useful here,
# but that option is available in Debian squeeze.

# This requires the bash version of printf (bashism)
printf -v ARGS "%q " "$@"
ssh garnet.ciffer.net notmuch $ARGS
