#!/bin/bash

# Run notmuch on remote host
#
# http://notmuchmail.org/remoteusage/
#
# Put (setq notmuch-command "notmuch-remote) in emacs configuration.

# Start a ControlMaster connection first:
# TODO: This will start a new ssh connection each time.
# ssh -Nf -o "ControlMaster yes" garnet.ciffer.net || true
#
# ControlPersist option (in OpenSSH 5.6) would be very useful here,
# but that option is available in Debian squeeze.

# This requires the bash version of printf (bashism)
printf -v ARGS "%q " "$@"
ssh garnet.ciffer.net notmuch $ARGS
