#!/bin/sh
# Print a string of five random words from the system dictionary
set -e

num=${1:-5}

grep '^[a-z]\{3,5\}$' /usr/share/dict/american-english |
sort -R |
head -n "$num" |
while read s; do
	echo -n "$s "
done
echo
