#!/bin/sh

# Set personal Gnome settings

# Gnome desktop

# Autohide panels
gconftool-2 --set --type bool /apps/panel/toplevels/bottom_panel_screen0/auto_hide true
gconftool-2 --set --type bool /apps/panel/toplevels/top_panel_screen0/auto_hide true

# Set hidden pannel size to zero
gconftool-2 --set --type int /apps/panel/toplevels/bottom_panel_screen0/auto_hide_size 0
gconftool-2 --set --type int /apps/panel/toplevels/top_panel_screen0/auto_hide_size 0

# Speed up hide/unhide
gconftool-2 --set --type bool /apps/panel/toplevels/bottom_panel_screen0/enable_animations false
gconftool-2 --set --type bool /apps/panel/toplevels/top_panel_screen0/enable_animations false

# Gnome terminal

# Disable alt key in gnome-terminal; I use alt on the command line
gconftool-2 --set --type bool /apps/gnome-terminal/global/use_mnemonics false

# Disable scrollbar
gconftool-2 --set --type bool /apps/gnome-terminal/profiles/Default/scrollbar_position false

# Disable menubar
gconftool-2 --set --type bool /apps/gnome-terminal/profiles/Default/default_show_menubar false
