#!/usr/bin/env python3

import ipaddress
import fileinput


def sortfn(s):
    return ipaddress.ip_address(s.strip())


if __name__ == '__main__':
    lines = sorted(fileinput.input(), key=sortfn)
    print(''.join(lines), end='')
