#!/bin/bash

BASE_URL=$1
VERSION_1=$2
VERSION_2=$3
: ${DIFF:=diff}

resources()
{
  curl -s -k -n "$BASE_URL/api/tm/$VERSION_1/config/active" | jq -r '.children[].href'
}

resources | while read r; do
  href_1=$(curl -s -k -n "$BASE_URL$r" | jq -r '.children[0].href')
  href_2=$(echo "$href_1" | sed "s|/$VERSION_1/|/$VERSION_2/|")

  diff=$($DIFF <(curl -skn "$BASE_URL$href_1" | jq . 2>/dev/null) \
              <(curl -skn "$BASE_URL$href_2" | jq . 2>/dev/null))

  if [ -n "$diff" ]; then
    echo "$href_1"
    echo "$diff"
  fi
done
