#!/bin/sh
# Expiring Cygwin/X clipboard
#
# Svend Sorensen

# Number of seconds to wait before clearing the clipboard
timeout=10

# Name of script
progname=$(basename $0)

setclip()
{
	case "$OSTYPE" in
	Cygwin)
		# Cygwin
		cat > /dev/clipboard
		;;
	*)
		# Linux
		cat | xclip -i
		;;
	esac
}

clearclip()
{
	case "$OSTYPE" in
	Cygwin)
		# Cygwin
		> /dev/clipboard
		;;
	*)
		# Linux
		xclip -i < /dev/null
		;;
	esac
}

# Clear the password if the program is cancelled
trap "clearclip; echo "cleared." 1>&2; exit 255" 2

setclip
echo -n "$progname: Clearing clipboard in $timeout seconds..." 1>&2
sleep $timeout
clearclip
echo "cleared." 1>&2
