#!/bin/sh
# Edit the contents of the clipboard
set -e

tmpfile=$(mktemp)
editor=${VISUAL:-vi}

xclip -o -selection clipboard > $tmpfile
$editor $tmpfile
xclip -i -selection clipboard < $tmpfile

rm -f $tmpfile
