#!/usr/bin/env python3

import argparse
import json
import sys
import yaml


def parse_args():
    parser = argparse.ArgumentParser(
        description='''Convert JSON to YAML''')
    parser.add_argument(
        '--multi',
        help='Process multiple YAML documents',
        action='store_true')
    return parser.parse_args()


if __name__ == '__main__':
    args = parse_args()
    if args.multi:
        data = yaml.load_all(sys.stdin)
        json = json.dumps(list(data))
    else:
        data = yaml.load(sys.stdin)
        json = json.dumps(data)
    print(json)
